import { MoviesResponse } from "./types";

export const exampleApiResponse: MoviesResponse = {
  page: 1,
  total_results: 185,
  total_pages: 10,
  results: [
    {
      popularity: 94.005,
      vote_count: 23169,
      video: false,
      poster_path: "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
      id: 24428,
      adult: false,
      backdrop_path: "/kwUQFeFXOOpgloMgZaadhzkbTI4.jpg",
      original_language: "en",
      original_title: "The Avengers",
      genre_ids: [28, 12, 878],
      title: "The Avengers",
      vote_average: 7.7,
      overview:
        "When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!",
      release_date: "2012-04-25",
    },
    {
      popularity: 195.965,
      vote_count: 15105,
      video: false,
      poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      id: 299534,
      adult: false,
      backdrop_path: "/orjiB3oUIsyz60hoEqkiGpy5CeO.jpg",
      original_language: "en",
      original_title: "Avengers: Endgame",
      genre_ids: [28, 12, 878],
      title: "Avengers: Endgame",
      vote_average: 8.3,
      overview:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      release_date: "2019-04-24",
    },
    {
      popularity: 211.69,
      vote_count: 19720,
      video: false,
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      id: 299536,
      adult: false,
      backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
      original_language: "en",
      original_title: "Avengers: Infinity War",
      genre_ids: [28, 12, 878],
      title: "Avengers: Infinity War",
      vote_average: 8.3,
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      release_date: "2018-04-25",
    },
    {
      popularity: 77.469,
      vote_count: 16544,
      video: false,
      poster_path: "/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
      id: 99861,
      adult: false,
      backdrop_path: "/8i6ZDk97Vyh0jHohMG4vFeFuKJh.jpg",
      original_language: "en",
      original_title: "Avengers: Age of Ultron",
      genre_ids: [28, 12, 878],
      title: "Avengers: Age of Ultron",
      vote_average: 7.3,
      overview:
        "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
      release_date: "2015-04-22",
    },
    {
      popularity: 38.812,
      vote_count: 215,
      video: false,
      poster_path: "/rXPxSAYf3FdQktnOtQnvhUPMhFp.jpg",
      id: 534490,
      adult: false,
      backdrop_path: "/pMREHTtqq5LZ797q127A9NZEfsN.jpg",
      original_language: "en",
      original_title: "Avengement",
      genre_ids: [28],
      title: "Avengement",
      vote_average: 6.7,
      overview:
        "While on a prison furlough, a lowly criminal evades his guards and returns to his old stomping ground to take revenge on the people who turned him into a cold blooded killer.",
      release_date: "2019-05-24",
    },
    {
      popularity: 21.408,
      vote_count: 440,
      video: false,
      poster_path: "/1p5thyQ4pCy876HpdvFARqJ62N9.jpg",
      id: 9320,
      adult: false,
      backdrop_path: "/fryen9fnjlm0YibKTDNGzWNBOSo.jpg",
      original_language: "en",
      original_title: "The Avengers",
      genre_ids: [878, 53],
      title: "The Avengers",
      vote_average: 4.3,
      overview:
        'British Ministry agent John Steed, under direction from "Mother", investigates a diabolical plot by arch-villain Sir August de Wynter to rule the world with his weather control machine. Steed investigates the beautiful Doctor Mrs. Emma Peel, the only suspect, but simultaneously falls for her and joins forces with her to combat Sir August.',
      release_date: "1998-08-13",
    },
    {
      popularity: 22.207,
      vote_count: 76,
      video: false,
      poster_path: "/1SbBKCbnULACOqWKN7eLfTu1gVm.jpg",
      id: 323660,
      adult: false,
      backdrop_path: "/tui9Z2QEoZSIPZMfpvPcNP9HIoA.jpg",
      original_language: "en",
      original_title: "Avengers Grimm",
      genre_ids: [28, 14],
      title: "Avengers Grimm",
      vote_average: 4.1,
      overview:
        'When Rumpelstiltskin destroys the Magic Mirror and escapes to the modern world, the four princesses of "Once Upon a Time"-Cinderella, Sleeping Beauty, Snow White, and Rapunzel-are sucked through the portal too. Well-trained and endowed with magical powers, the four women must fight Rumpelstiltskin and his army of thralls before he enslaves everyone on Earth.',
      release_date: "2015-03-17",
    },
    {
      popularity: 22.829,
      vote_count: 220,
      video: false,
      poster_path: "/iMCkGHVrYRdqKROPRPmVaJVSlg3.jpg",
      id: 14609,
      adult: false,
      backdrop_path: "/p5uTZHrXwWX0j9dYZK8yx22sO7T.jpg",
      original_language: "en",
      original_title: "Ultimate Avengers: The Movie",
      genre_ids: [28, 12, 16, 878],
      title: "Ultimate Avengers: The Movie",
      vote_average: 6.7,
      overview:
        "When a nuclear missile was fired at Washington in 1945, Captain America managed to detonate it in the upper atmosphere. But then he fell miles into the icy depths of the North Atlantic, where he remained lost for over sixty years. But now, with the world facing the very same evil, Captain America must rise again as our last hope for survival.",
      release_date: "2006-02-21",
    },
    {
      popularity: 20.045,
      id: 257346,
      video: false,
      vote_count: 133,
      vote_average: 6.1,
      title: "Avengers Confidential: Black Widow & Punisher",
      release_date: "2014-03-25",
      original_language: "ja",
      original_title:
        "アベンジャーズ コンフィデンシャル：ブラック・ウィドウ ＆ パニッシャー",
      genre_ids: [16, 878, 28],
      backdrop_path: "/kI1AdjSl2o038FQRZTuOqOlZ9VN.jpg",
      adult: false,
      overview:
        "When the Punisher takes out a black-market weapons dealer, he stumbles upon a far-reaching terrorist plot devised by a group known as Leviathan.",
      poster_path: "/4Au5QB55O5DWW0hXw1SQQDFIjAp.jpg",
    },
    {
      popularity: 33.089,
      id: 1771,
      video: false,
      vote_count: 15547,
      vote_average: 6.9,
      title: "Captain America: The First Avenger",
      release_date: "2011-07-22",
      original_language: "en",
      original_title: "Captain America: The First Avenger",
      genre_ids: [28, 12, 878],
      backdrop_path: "/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg",
      adult: false,
      overview:
        "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
      poster_path: "/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg",
    },
    {
      popularity: 21.389,
      vote_count: 184,
      video: false,
      poster_path: "/sMFyYZR9krqcQC99G6jnb10Zv4P.jpg",
      id: 14611,
      adult: false,
      backdrop_path: "/z1P4mdithLear5Du48jbsIr12b7.jpg",
      original_language: "en",
      original_title: "Ultimate Avengers 2: Rise of the Panther",
      genre_ids: [28, 12, 16, 878],
      title: "Ultimate Avengers 2: Rise of the Panther",
      vote_average: 6.6,
      overview:
        "Mysterious Wakanda lies in the darkest heart of Africa, unknown to most of the world. An isolated land hidden behind closed borders, fiercely protected by its young king - the Black Panther. But when brutal alien invaders attack, the threat leaves the Black Panther with no option but to go against the sacred decrees of his people and ask for help from outsiders.",
      release_date: "2006-08-08",
    },
    {
      popularity: 6.626,
      vote_count: 10,
      video: false,
      poster_path: "/kHQ81KIAq8kD9NfUmHjTgAahoCW.jpg",
      id: 47369,
      adult: false,
      backdrop_path: "/mQZ0jXbTfY4RAfPPp3iuH6vtKcX.jpg",
      original_language: "en",
      original_title: "Avenger",
      genre_ids: [28, 53, 10770],
      title: "Avenger",
      vote_average: 6.1,
      overview:
        "After his own daughter was killed in Panama in 1994, former CIA agent Calvin Dexter became a private 'specialist' in cases which wouldn't reach justice trough the regular legal channels. Two years later he accepts to find Richard 'Ricky' Edmunds for his pa, influential rich businessman Stephen Edmonds. Ricky for a private Canadian war victims charity in Bosnia and went missing. Dexter discovers Ricky was beaten to pulp and drowned for no other crime then helping street boys from the other side by Zoran Zilic and his Serbian paramilitary 'order'. He offers Steven to 'finish the job' as such war criminals don't go to trial. But deputy CIA director Paul Devereaux cares only for a nuclear arms project he wants to use Zilic for. So CIA troubleshooter Frank McBride is ordered to protect him and handle Dexter.",
      release_date: "2006-04-09",
    },
    {
      popularity: 11.885,
      id: 15239,
      video: false,
      vote_count: 291,
      vote_average: 6.4,
      title: "The Toxic Avenger",
      release_date: "1984-05-01",
      original_language: "en",
      original_title: "The Toxic Avenger",
      genre_ids: [878, 28, 35, 27],
      backdrop_path: "/UlFiZRQO0bR6mayux42KrLEQ4Y.jpg",
      adult: false,
      overview:
        "Tromaville has a monstrous new hero. The Toxic Avenger is born when mop boy Melvin Junko falls into a vat of toxic waste. Now evildoers will have a lot to lose.",
      poster_path: "/qRbAr8yilTnXssmk52po7RyqZSH.jpg",
    },
    {
      popularity: 17.425,
      vote_count: 134,
      video: false,
      poster_path: "/fpG1NDbcLV2a7c8X7LC4FPISBT7.jpg",
      id: 14613,
      adult: false,
      backdrop_path: "/8N91uYwrr1uepEKbmym1tgfXlzS.jpg",
      original_language: "en",
      original_title: "Next Avengers: Heroes of Tomorrow",
      genre_ids: [16, 10751],
      title: "Next Avengers: Heroes of Tomorrow",
      vote_average: 6.7,
      overview:
        "The children of the Avengers hone their powers and go head to head with the very enemy responsible for their parents' demise.",
      release_date: "2008-09-02",
    },
    {
      popularity: 23.868,
      vote_count: 13,
      video: false,
      poster_path: "/jcoaZNyoN2l8G2RCTgcogaj525G.jpg",
      id: 380764,
      adult: false,
      backdrop_path: "/dRgQIJabgrVxAb8seiSyLXoacw7.jpg",
      original_language: "id",
      original_title: "Valentine",
      genre_ids: [28, 80, 878, 53],
      title: "Valentine",
      vote_average: 4.9,
      overview:
        "Batavia City, a beautiful city that no longer safely inhabited. Robbery, violence, and a variety of increasingly rampant criminality. In the midst of this chaotic city, Srimaya, a cafe waitress who dreams of becoming an actress never thought that dream would change her life. Her meeting with Bono, a film director and his friend, Wawan, will take her on a dangerous adventure full of thrilling action with lives at stake. Turning her from an ordinary girl into Batavia City heroine of hope, Valentine.",
      release_date: "2017-11-23",
    },
    {
      popularity: 8.898,
      vote_count: 65,
      video: false,
      poster_path: "/evB9pQHF1qR2UQtuApbaigcZwG5.jpg",
      id: 27601,
      adult: false,
      backdrop_path: "/iXzTZ6oKXXrbTcibXIuIXQaikD9.jpg",
      original_language: "en",
      original_title: "Citizen Toxie: The Toxic Avenger IV",
      genre_ids: [35, 27],
      title: "Citizen Toxie: The Toxic Avenger IV",
      vote_average: 6.5,
      overview:
        "When the notorious Diaper Mafia take hostage the Tromaville School for the Very Special, only the Toxic Avenger and his morbidly obese sidekick Lardass can save Tromaville.",
      release_date: "2001-11-01",
    },
    {
      popularity: 11.196,
      vote_count: 145,
      video: false,
      poster_path: "/hl4mI28D4NhE6ePNgPojQuyEYw7.jpg",
      id: 13437,
      adult: false,
      backdrop_path: "/9hwOuM8Wh0CB2czZHL8uSpw1hp8.jpg",
      original_language: "en",
      original_title: "Avenging Angelo",
      genre_ids: [28, 35, 80],
      title: "Avenging Angelo",
      vote_average: 5.5,
      overview:
        "A woman who has recently discovered that she is the daughter of Angelo, a major mafia boss, decides to wreak vengeance when he is killed by a hitman. She's aided by his faithful bodyguard, with whom she soon falls in love.",
      release_date: "2002-08-30",
    },
    {
      popularity: 9.099,
      vote_count: 80,
      video: false,
      poster_path: "/uJ5pZZJW2bHo5tKFARTMpo7js3i.jpg",
      id: 28165,
      adult: false,
      backdrop_path: "/heajLgHXV87WPIp1rvA53qrABYj.jpg",
      original_language: "en",
      original_title: "The Toxic Avenger Part II",
      genre_ids: [28, 35, 27],
      title: "The Toxic Avenger Part II",
      vote_average: 5.4,
      overview:
        "The Toxic Avenger is lured to Tokyo, Japan by the evil corporation Apocalypse Inc. So while the Toxic Avenger is fighting crime in Tokyo, Apocalypse Inc. spread evil in Tromaville.",
      release_date: "1989-02-24",
    },
    {
      popularity: 13.414,
      vote_count: 42,
      video: false,
      poster_path: "/xUBZNoY7idPfqKZepnDEv7Qc8GC.jpg",
      id: 368304,
      adult: false,
      backdrop_path: "/zvjBC9guJVw32bZu4ODp6wzJ9Vi.jpg",
      original_language: "en",
      original_title: "LEGO Marvel Super Heroes: Avengers Reassembled!",
      genre_ids: [16],
      title: "LEGO Marvel Super Heroes: Avengers Reassembled!",
      vote_average: 6.3,
      overview:
        "In \"LEGO Marvel Super Heroes: Avengers Reassembled!,\" the Avengers prepare for a party at Stark Tower and notice that Iron Man is acting strange. After some investigation, they discover that the evil Ultron has taken control of Iron Man and his armor as part of his scheme to take over the world. It's up to Captain America, the Hulk, Thor, Vision, Black Widow, Hawkeye and their friends (Spider-Man, Iron Spider, and special guest star Ant-Man) to rescue Iron Man from Ultron's clutches and defeat the super villain before he causes even more destruction and chaos.",
      release_date: "2015-11-16",
    },
    {
      popularity: 8.627,
      vote_count: 36,
      video: false,
      poster_path: "/xfAcu74DRQXeM9XqFcE5MrSRzYP.jpg",
      id: 521720,
      adult: false,
      backdrop_path: "/mdSrxMg4l6a76AFoBWmu7Q1X4Rt.jpg",
      original_language: "en",
      original_title: "Avengers Grimm: Time Wars",
      genre_ids: [28, 12, 14],
      title: "Avengers Grimm: Time Wars",
      vote_average: 4.7,
      overview:
        "When Rumpelstiltskin tries to take over Earth once and for all, The Avengers Grimm must track him down through time in order to defeat him.",
      release_date: "2018-05-01",
    },
  ],
};
